theme: jekyll-theme-hacker
name: litleleprikon <iam@litleleprikon.me>
title: '[litleleprikon]'
description: 'Blog of one technomaniac'
show_downloads: false
baseurl: ""
paginate: 10
gems:
  - octopress-paginate
  - jekyll-sitemap
google_analytics: UA-90618237-1
