theme: jekyll-theme-hacker
title: [\[litleleprikon\] blog of one technomaniac]
description: [I am software engineer and “Secure Systems and Networks Engineering” student from Innopolis, Russia. And this is my temporary blog until I create it in React.)]
show_downloads: false